Modified push.yml

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -4,11 +4,11 @@ on:
   push:
     branches: [ main, master ]
     paths-ignore:
-      - '**.md'
+        - '**.md'
   pull_request:
     branches: [ main, master ]
     paths-ignore:
-      - '**.md'
+        - '**.md'
 
 jobs:
   build-and-push:
@@ -25,11 +25,18 @@ jobs:
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
 
-    - name: Force push to PWS
+    - name: Check PWS remote, pull, merge, and push
       env:
         PWS_URL: ${{ secrets.PWS_URL }}
       run: |
-        git remote add pws $PWS_URL
-        git fetch pws
-        git reset --hard origin/main
-        git push pws main:master --force
+          echo "Creating temporary branch"
+          git checkout -b tmp
+
+          # Push to master branch and capture the output
+          push_output=$(git push $PWS_URL tmp:master 2>&1)
+          if [[ $? -ne 0 ]]; then
+            echo "Push failed with output: $push_output"
+            echo "Error: Unable to push changes. Please check the error message above and resolve any conflicts manually."
+            exit 1
+          fi
+          echo "Push successful with output: $push_output"
